name: password_manager
description: Password Manager App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  cupertino_icons:
  dartz: ^0.10.1
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  handy_extensions: ^0.1.5+3
  intl: ^0.18.0
  json_annotation: ^4.8.1
  localregex:
  modal_bottom_sheet: ^3.0.0-pre
  otp_text_field: ^1.1.3
  package_info_plus: ^4.0.2
  path: ^1.8.0
  path_provider:
  permission_handler: ^10.2.0
  relative_scale: ^2.0.0
  sentry_dio: ^7.8.0
  sentry_flutter: ^7.7.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable:
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: 'Poppins'
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
